### ISSUE TITLE
Does not seem t o work in a safari browser on a computer.

### ISSUE THREAD

**Issue by connecties** [marloustolk/irmpier#1]
Running this game on a safari browser on an apple computer does not seem to work.

If you change the listen function in app.component.ts to:

```
  listen(event: Event) {
    if ('touches' in event) {
      this.directionService.handleTouchEvent(event as TouchEvent);
    } else {
      this.directionService.handleEvent((event as KeyboardEvent).key);
    }
  }
```

It will also work in this browser.
I have not been able to test this on a mobile device so before incorporating this please test in a mobile browser.

**Comment by marloustolk** [comment]
Works like a charm 🥇
